### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by fernandopereiralisboa** [TimLuq/wsdl-to-ts#4]
try: 
wsdl-to-ts https://www.tsbestcardsystems.net/CEMSGlobalServices/CEMSGS.asmx?wsdl

result:
{ Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:637:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' 
}

**Comment by TimLuq** [comment]
This issue must have been buried somewhere in my inbox, my apologies for a late reply.

That problem is out of scope for this project. The TLS connections are handled by the builtin module provided by node. Try updating your node version and verify that your connection doesn't have some MITM injecting faulty certificates.
